# This file contains the fastlane.tools configuration
# You can find the documentation at https://docs.fastlane.tools
#
# For a list of all available actions, check out
#
#     https://docs.fastlane.tools/actions
#
# For a list of all available plugins, check out
#
#     https://docs.fastlane.tools/plugins/available-plugins
#

# Uncomment the line if you want fastlane to automatically update itself
# update_fastlane

default_platform(:ios)

KEY_ID = ENV["KEY_ID"]
ISSUER_ID = ENV["ISSUER_ID"]
KEY_CNONTENT = ENV["KEY_CONTENT"]
GIT_BASE_64_KEY = ENV["GIT_BASE_64_KEY"]
PRIVATE_KEY = ENV["PRIVATE_KEY"]

platform :ios do
  desc "Push a new release build to the App Store"
  lane :release do
    setup_ci # creates a temporary keychain
    sync_code_signing(type: "appstore", readonly: true, git_basic_authorization: GIT_BASE_64_KEY) # alias for "match". "sync_code_signing" = "match"
    increment_build_number(xcodeproj: "Downloader.xcodeproj")
    build_app(workspace: "Downloader.xcworkspace", scheme: "Downloader")
    
    api_key = app_store_connect_api_key(
      key_id: KEY_ID,
      issuer_id: ISSUER_ID,
      key_content: KEY_CNONTENT,
      duration: 1200, # optional (maximum 1200)
      in_house: false # optional but may be required if using match/sigh
    )

    upload_to_app_store(  # upload your app to App Store Connect
        api_key: api_key,
        run_precheck_before_submit: false,
        submit_for_review: false,
        automatic_release: false,
        force: true, # Skip HTMl report verification
        skip_metadata: true,
        skip_screenshots: true,
    )                 
  end
end
